name: build-demo

on:
  push:
    tags:
      - 'demo-*'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04, macos-13, windows-2022]
        python-version: ['3.11']
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Build with PyInstaller
        run: |
          pyinstaller --noconfirm --windowed --name NOAGridApp noa_app/__main__.py
      - name: Archive artifact (zip)
        if: runner.os != 'Windows'
        run: |
          cd dist
          zip -r NOAGridApp-${{ runner.os }}.zip NOAGridApp
      - name: Archive artifact (7z)
        if: runner.os == 'Windows'
        shell: bash
        run: |
          cd dist
          7z a NOAGridApp-Windows.zip NOAGridApp
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: NOAGridApp-${{ runner.os }}
          path: dist/NOAGridApp-*.zip
