name: Mac demo

on:
  push:
    tags:
      - 'demo-mac-*'

jobs:
  compat:
    name: Compatibility check (macOS)
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Headless import checks
        env:
          QT_QPA_PLATFORM: offscreen
        run: |
          python - <<'PY'
          import sys, platform
          print('Python', sys.version)
          print('Platform', platform.platform())
          import PySide6
          from PySide6.QtWidgets import QApplication
          import PIL, numpy, pandas, openpyxl
          from pathlib import Path
          sys.path.insert(0, str(Path('standalone_app').absolute()))
          import run_app
          print('Imports OK')
          PY

  build:
    name: Build installer (macOS)
    needs: compat
    runs-on: macos-13
    env:
      MACOS_CERT_P12: ${{ secrets.MACOS_CERT_P12 }}
      MACOS_CERT_PASSWORD: ${{ secrets.MACOS_CERT_PASSWORD }}
      MACOS_DEVELOPER_ID_APP: ${{ secrets.MACOS_DEVELOPER_ID_APP }}
      MACOS_TEAM_ID: ${{ secrets.MACOS_TEAM_ID }}
      MACOS_NOTARIZATION_APPLE_ID: ${{ secrets.MACOS_NOTARIZATION_APPLE_ID }}
      MACOS_NOTARIZATION_PASSWORD: ${{ secrets.MACOS_NOTARIZATION_PASSWORD }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Set up venv
        run: |
          python -m venv .venv
          source .venv/bin/activate
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller
          pip install 'numpy<2' || true
      - name: Build with PyInstaller
        env:
          QT_QPA_PLATFORM: offscreen
        run: |
          source .venv/bin/activate
          python -m PyInstaller --noconfirm --windowed --name SpermVerificationApp \
            --hidden-import PySide6.QtNetwork \
            --collect-data PySide6 \
            --collect-all PIL \
            --exclude-module PySide6.Qt3DAnimation --exclude-module PySide6.Qt3DCore --exclude-module PySide6.Qt3DRender --exclude-module PySide6.Qt3DExtras --exclude-module PySide6.Qt3DInput --exclude-module PySide6.Qt3DLogic \
            --exclude-module PySide6.QtWebEngineCore --exclude-module PySide6.QtWebEngineWidgets --exclude-module PySide6.QtWebEngineQuick \
            --exclude-module PySide6.QtCharts --exclude-module PySide6.QtDataVisualization \
            --exclude-module PySide6.QtMultimedia --exclude-module PySide6.QtMultimediaWidgets \
            --exclude-module PySide6.QtQuick --exclude-module PySide6.QtQuickWidgets --exclude-module PySide6.QtQuickControls2 --exclude-module PySide6.QtQuick3D \
            --exclude-module PySide6.QtOpenGL --exclude-module PySide6.QtOpenGLWidgets \
            --exclude-module PySide6.QtHelp --exclude-module PySide6.QtDesigner --exclude-module PySide6.QtGraphs \
            --exclude-module PySide6.QtHttpServer --exclude-module PySide6.QtLocation --exclude-module PySide6.QtPositioning \
            --exclude-module PySide6.QtRemoteObjects --exclude-module PySide6.QtSensors --exclude-module PySide6.QtSerialBus --exclude-module PySide6.QtSerialPort \
            --exclude-module PySide6.QtSpatialAudio --exclude-module PySide6.QtPdf --exclude-module PySide6.QtPdfWidgets \
            --exclude-module PySide6.QtSql --exclude-module PySide6.QtSvg --exclude-module PySide6.QtSvgWidgets \
            --exclude-module PySide6.QtTest --exclude-module PySide6.QtUiTools --exclude-module PySide6.QtWebSockets \
            --exclude-module PySide6.QtBluetooth --exclude-module PySide6.QtNfc --exclude-module PySide6.QtNetworkAuth --exclude-module PySide6.QtDBus --exclude-module PySide6.QtAsyncio \
            standalone_app/run_app.py
      - name: Code sign + Notarize (macOS)
        if: ${{ env.MACOS_CERT_P12 != '' && env.MACOS_CERT_PASSWORD != '' && env.MACOS_DEVELOPER_ID_APP != '' && env.MACOS_TEAM_ID != '' && env.MACOS_NOTARIZATION_APPLE_ID != '' && env.MACOS_NOTARIZATION_PASSWORD != '' }}
        run: |
          set -euo pipefail
          APP="dist/SpermVerificationApp.app"
          KEYCHAIN=build.keychain
          echo "$MACOS_CERT_P12" | base64 -d > cert.p12
          security create-keychain -p temp "$KEYCHAIN"
          security default-keychain -s "$KEYCHAIN"
          security unlock-keychain -p temp "$KEYCHAIN"
          security import cert.p12 -k "$KEYCHAIN" -P "$MACOS_CERT_PASSWORD" -T /usr/bin/codesign
          security set-key-partition-list -S apple-tool:,apple: -s -k temp "$KEYCHAIN"
          codesign --deep --force --options runtime --sign "$MACOS_DEVELOPER_ID_APP" "$APP"
          ditto -c -k --sequesterRsrc --keepParent "$APP" SpermVerificationApp.zip
          xcrun notarytool submit SpermVerificationApp.zip --apple-id "$MACOS_NOTARIZATION_APPLE_ID" --password "$MACOS_NOTARIZATION_PASSWORD" --team-id "$MACOS_TEAM_ID" --wait
          xcrun stapler staple "$APP"
      - name: Archive artifact
        run: |
          cd dist
          ditto -c -k --sequesterRsrc --keepParent SpermVerificationApp.app SpermVerificationApp-macOS.zip
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: SpermVerificationApp-macOS
          path: dist/SpermVerificationApp-macOS.zip


